name: Publish

on:
  push:
    branches: [master]

env:
  NPM_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
          registry-url: https://registry.npmjs.org/
          scope: '@ramseyinhouse'
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
      - run: |
          git config user.name "RamseyInHouse Open Source"
          git config user.email "opensource@ramseysolutions.com"
          yarn install
          yarn build
          yarn run lerna publish --yes
